### ISSUE TITLE
Updated files ?

### ISSUE THREAD

**Issue by ArtOS-Developper** [alvess09/Hackintosh-dell-3583#1]
Hello,
I am currently rebuilding my hackintosh on my Dell Inspiron 15 3583.
I managed to boot macOS Catalina, but I only have 7Mb of video memory (with the UHD 620)
So I came across your repo. So I copied your OpenCore boot files, but it leaves me on a critical error.
Can you update the files?
Thanks

**Comment by alvess09** [comment]
Hi Arthur! so the files I used I found in this repository  https://github.com/jkcoxson/Inspiron-3583-Hackintosh, maybe you can find help there the staff there are more understanding of these questions about Hackintosh and open core.
I´m not currently using mine I had some problems with power management and it cost me a little battery life, but if I´m not being able to download any of the files tell me which I send you a direct link to the file, I would like to help more

**Comment by ArtOS-Developper** [comment]
Thank you for your answer.
In fact thanks to Jkcoxson's repo I was able to do it but I can't get the whole video memory. So I looked for fixes but none worked. I came across your repo and saw the macOS system information with the 2048MB of video memory. So I tried with your repo but impossible to start open core because of the missing drivers apparently. I wanted to know if it was possible that you send me the boot files
Thanks
PS: I have the model with the Core i3, without dedicated graphics card if ever

**Comment by alvess09** [comment]
https://files.fm/u/6h7b75aq6

**Comment by alvess09** [comment]
maybe you should  remove files and past new files EFI and kexts to initialization, in this link is files  I used

**Comment by alvess09** [comment]
https://files.fm/u/fupbatz54 here this is other files try it

**Comment by ArtOS-Developper** [comment]
Thanks I will try this when I can (surely this weekend)
